spring:
  application:
    name: springAi
  ai:
    openai:
      api-key: YOUR_API_KEY
    ollama:
      chat:
        options:
          model: MODEL
    retry:
      max-attempts: 3
      backoff:
        multiplier: 2
        initial-interval: 10000ms
        max-interval: 20000

gemini:
  api-url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent" || YOUR_API_URL
  api-key: YOUR_API_KEY

server:
  port: 8000