spring:
  application:
    name: springAi
  ai:
    openai:
      api-key: API_KEY
    ollama:
      chat:
        options:
          model: MODEL
    retry:
      max-attempts: 3
      backoff:
        multiplier: 2
        initial-interval: 10000ms
        max-interval: 20000

server:
  port: 8000